"""
Example 04: Architecture phase — store and list proposals
===========================================================
Simulates the bisset-architect phase:
  1. Retrieve the architecture phase prompt
  2. Store three paradigm proposals (OOP, Functional, Data-Oriented)
  3. List proposals with scores
  4. Add tasks based on the winning proposal

Run:
    python docs/examples/04_architecture.py <session_id>
"""

import json
import sys
import requests

BASE_URL = "http://localhost:8765"


def unwrap(response: requests.Response) -> dict:
    response.raise_for_status()
    body = response.json()
    if body.get("is_error"):
        error_text = body["content"][0]["text"]
        error_data = json.loads(error_text)
        raise RuntimeError(f"{error_data.get('error')} ({error_data.get('code')})")
    return json.loads(body["content"][0]["text"])


# Simplified example proposals (in production these are generated by Claude)
PROPOSALS = [
    {
        "paradigm": "oop",
        "content": (
            "# OOP Architecture\n\n"
            "## Core Entities\n"
            "- `User` — authentication + profile\n"
            "- `Project` — owned by User, has many Tasks\n"
            "- `Task` — status, deadline, assignee\n\n"
            "## Services\n"
            "- `AuthService` — OAuth2 via GitHub\n"
            "- `ProjectService` — CRUD + sharing\n"
            "- `NotificationService` — deadline reminders\n"
        ),
        "score": 91.5,
    },
    {
        "paradigm": "functional",
        "content": (
            "# Functional Architecture\n\n"
            "## Pure functions\n"
            "- `create_task(project_id, title, deadline) -> Task`\n"
            "- `assign_task(task, user) -> Task`\n"
            "- `advance_status(task, new_status) -> Task | Error`\n\n"
            "## Immutable state via event sourcing\n"
        ),
        "score": 84.0,
    },
    {
        "paradigm": "data",
        "content": (
            "# Data-Oriented Architecture\n\n"
            "## Tables as the design unit\n"
            "- `users(id, github_id, email, created_at)`\n"
            "- `projects(id, owner_id, name, created_at)`\n"
            "- `tasks(id, project_id, title, status, deadline)`\n\n"
            "## Access patterns drive index design\n"
        ),
        "score": 78.5,
    },
]

# Tasks derived from the winning OOP proposal
TASKS = [
    {
        "title": "Implement GitHub OAuth2 login",
        "description": "Integrate GitHub OAuth2 flow using FastAPI + httpx.",
        "acceptance_criteria": (
            "Given a user visits /auth/github\n"
            "When they authorise the app\n"
            "Then they are redirected back with a JWT session cookie"
        ),
    },
    {
        "title": "Create Project CRUD API",
        "description": "REST endpoints: POST /projects, GET /projects, PATCH /projects/{id}, DELETE /projects/{id}.",
        "acceptance_criteria": (
            "Given an authenticated user\n"
            "When they POST /projects with a valid name\n"
            "Then a project is created and returned with HTTP 201"
        ),
    },
    {
        "title": "Build Task management endpoints",
        "description": "Nested under /projects/{id}/tasks — full CRUD + status transitions.",
        "acceptance_criteria": (
            "Given a project exists\n"
            "When a user creates a task with a deadline\n"
            "Then the task appears in GET /projects/{id}/tasks"
        ),
    },
]


def main(session_id: str):
    print(f"Architecture phase for session: {session_id}\n{'─' * 45}")

    # ── 1. Fetch the architecture phase prompt ────────────────────────────────
    prompt_data = unwrap(requests.get(f"{BASE_URL}/prompts/phase/architecture"))
    print(f"Phase prompt  : {prompt_data['prompt'][:80]}…\n")

    # ── 2. Store proposals ────────────────────────────────────────────────────
    print("Storing proposals:")
    for p in PROPOSALS:
        result = unwrap(
            requests.post(
                f"{BASE_URL}/workflow_store_proposal/{session_id}",
                params={"paradigm": p["paradigm"], "content": p["content"], "score": p["score"]},
            )
        )
        print(f"  [{p['paradigm']:10s}]  score={p['score']:5.1f}  id={result['proposal_id']}")

    # ── 3. List proposals ─────────────────────────────────────────────────────
    listing = unwrap(requests.get(f"{BASE_URL}/workflow_list_proposals/{session_id}"))
    proposals = listing["proposals"]
    winning = max(proposals, key=lambda x: (x["score"] or 0))
    print(f"\nWinning paradigm: {winning['paradigm']} (score {winning['score']})")

    # ── 4. Inject tasks from winning proposal ─────────────────────────────────
    print("\nInjecting tasks:")
    for t in TASKS:
        result = unwrap(
            requests.post(
                f"{BASE_URL}/workflow_add_task/{session_id}",
                params={
                    "title": t["title"],
                    "description": t["description"],
                    "acceptance_criteria": t["acceptance_criteria"],
                },
            )
        )
        print(f"  [{result['task_id']}] {t['title']}")

    return session_id


if __name__ == "__main__":
    if len(sys.argv) < 2:
        print("Usage: python 04_architecture.py <session_id>", file=sys.stderr)
        sys.exit(1)

    main(sys.argv[1])
    print(f"\nNext step: python docs/examples/05_implement_task.py {sys.argv[1]}")
